### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by geeflaxx** [erikonasz/IG-Ultimate#1]
Thanks for your script.

I get following error: 
```

Traceback (most recent call last):
  File "/home/user/PycharmProjects/A1/release/main.py", line 38, in <module>
    login()
  File "/home/user/PycharmProjects/A1/release/main.py", line 24, in login
    button = driver.find_element(By.XPATH, '//button[text()="Only allow essential cookies"]')
  File "/home/user/anaconda3/envs/A1/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/user/anaconda3/envs/A1/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/home/user/anaconda3/envs/A1/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()="Only allow essential cookies"]"}
  (Session info: chrome=107.0.5304.121)
Stacktrace:
#0 0x5562f58ea794 <unknown>
#1 0x5562f56b7f21 <unknown>
#2 0x5562f56f9055 <unknown>
#3 0x5562f56f9191 <unknown>
#4 0x5562f573b065 <unknown>
#5 0x5562f57207bd <unknown>
```

you too?

**Comment by erikonasz** [comment]
Hey there! It seems that the button 'Only allow essential cookies' is not located. Is the Instagram page in ENG?
